baseUrl: "https://balintfodor.github.io/"
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: bf_brn.dmp

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    # dateFormat:
    #     published: Jan 02, 2006
    #     lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        subtitle: a place for my brain dumps
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/balintfodor
          params:
              icon: brand-github
